service: socials-backend

provider:
  name: aws
  runtime: python3.9
  region: us-east-2
  stage: prod
  timeout: 30
  memorySize: 512
  environment:
    DEFAULT_REGION: us-east-2
    BEDROCK_REGION: us-east-1
    S3_BUCKET: socials-aws-1
    X_API_KEY: ${env:X_API_KEY}
    X_API_KEY_SECRET: ${env:X_API_KEY_SECRET}
    X_BEARER_TOKEN: ${env:X_BEARER_TOKEN}
    X_ACCESS_TOKEN: ${env:X_ACCESS_TOKEN}
    X_ACCESS_TOKEN_SECRET: ${env:X_ACCESS_TOKEN_SECRET}
    LINKEDIN_CLIENT_ID: ${env:LINKEDIN_CLIENT_ID}
    LINKEDIN_CLIENT_SECRET: ${env:LINKEDIN_CLIENT_SECRET}
  iam:
    role:
      statements:
        - Effect: Allow
          Action:
            - bedrock:*
            - s3:*
            - dynamodb:*
            - secretsmanager:GetSecretValue
            - logs:CreateLogGroup
            - logs:CreateLogStream
            - logs:PutLogEvents
          Resource: "*"

functions:
  api:
    handler: lambda_handler.handler
    events:
      - httpApi:
          path: /{proxy+}
          method: ANY
          cors:
            allowOrigins:
              - https://socials.dataopslabs.com
              - http://localhost:5173
            allowHeaders:
              - Content-Type
              - Authorization
              - X-User-Id
            allowMethods:
              - GET
              - POST
              - PUT
              - DELETE
              - OPTIONS
              - PATCH
      - httpApi:
          path: /
          method: ANY
          cors:
            allowOrigins:
              - https://socials.dataopslabs.com
              - http://localhost:5173
            allowHeaders:
              - Content-Type
              - Authorization
              - X-User-Id
            allowMethods:
              - GET
              - POST
              - PUT
              - DELETE
              - OPTIONS
              - PATCH

plugins:
  - serverless-python-requirements

custom:
  pythonRequirements:
    dockerizePip: true
    slim: true
    strip: false
    noDeps: false
    pipCmdExtraArgs:
      - --no-cache-dir
