AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: Socials Backend API

Globals:
  Function:
    Timeout: 30
    MemorySize: 512
    Runtime: python3.9
    Environment:
      Variables:
        DEFAULT_REGION: us-east-2
        BEDROCK_REGION: us-east-1
        S3_BUCKET: socials-aws-1

Resources:
  SocialsApi:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: .
      Handler: lambda_handler.handler
      Events:
        ApiEvent:
          Type: Api
          Properties:
            Path: /{proxy+}
            Method: ANY
            RestApiId: !Ref SocialsRestApi
        RootApiEvent:
          Type: Api
          Properties:
            Path: /
            Method: ANY
            RestApiId: !Ref SocialsRestApi
      Environment:
        Variables:
          X_API_KEY: !Ref XApiKey
          X_API_KEY_SECRET: !Ref XApiKeySecret
          X_BEARER_TOKEN: !Ref XBearerToken
          X_ACCESS_TOKEN: !Ref XAccessToken
          X_ACCESS_TOKEN_SECRET: !Ref XAccessTokenSecret
          LINKEDIN_CLIENT_ID: !Ref LinkedInClientId
          LINKEDIN_CLIENT_SECRET: !Ref LinkedInClientSecret
      Policies:
        - Version: '2012-10-17'
          Statement:
            - Effect: Allow
              Action:
                - bedrock:*
                - s3:*
                - dynamodb:*
                - secretsmanager:GetSecretValue
                - logs:CreateLogGroup
                - logs:CreateLogStream
                - logs:PutLogEvents
              Resource: '*'

  SocialsRestApi:
    Type: AWS::Serverless::Api
    Properties:
      StageName: prod
      Cors:
        AllowMethods: "'GET,POST,PUT,DELETE,OPTIONS,PATCH'"
        AllowHeaders: "'Content-Type,Authorization,X-User-Id'"
        AllowOrigin: "'https://socials.dataopslabs.com'"
        AllowCredentials: true

Parameters:
  XApiKey:
    Type: String
    Default: AzwOJGOLdGJJKJHGFDSAzxcvbnm
    NoEcho: true
  XApiKeySecret:
    Type: String
    Default: 9P8o7i6u5y4t3r2e1w0q9a8s7d6f5g4h3j2k1l0m9n8b7v6c5x4z3a2s1d0f9g8h7j6k5l4
    NoEcho: true
  XBearerToken:
    Type: String
    Default: AAAAAAAAAAAAAAAAAAAAAMLheAAAAAAA0%2BuSeid%2BULvsea4JtiGRiSDSJSI%3DEUifiRBkKG5E2XzMDjRfl76ZC9Ub0wnz4XsNiRVBChTYbJcE3F
    NoEcho: true
  XAccessToken:
    Type: String
    Default: 1234567890123456789-AbCdEfGhIjKlMnOpQrStUvWxYz1234567890Ab
    NoEcho: true
  XAccessTokenSecret:
    Type: String
    Default: 1a2b3c4d5e6f7g8h9i0j1k2l3m4n5o6p7q8r9s0t1u2v3w4x5y6z
    NoEcho: true
  LinkedInClientId:
    Type: String
    Default: 86vkop6nen6kvi
    NoEcho: true
  LinkedInClientSecret:
    Type: String
    Default: WPL_AP1.AL44Zi3CwnFkpAz2.1uCXAw==
    NoEcho: true

Outputs:
  SocialsApiUrl:
    Description: "API Gateway endpoint URL for Prod stage"
    Value: !Sub "https://${SocialsRestApi}.execute-api.${AWS::Region}.amazonaws.com/prod/"
    Export:
      Name: SocialsApiUrl
